// Fetches Google Scholar profile stats and per-paper citation counts, then
// regenerates src/data/scholar-live.ts. Run daily by
// .github/workflows/update-scholar.yml; can also be run locally:
//   node scripts/fetch-scholar.mjs
//
// Google Scholar has no API and rate-limits datacenter IPs, so this scrapes
// the public profile page and fails loudly (non-zero exit) when blocked or
// when the HTML structure changes — in that case the previously committed
// data stays in place.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCHOLAR_USER = "7DWbsPUAAAAJ";
const PROFILE_URL = `https://scholar.google.com/citations?user=${SCHOLAR_USER}&hl=en&pagesize=100&sortby=citedby`;

const res = await fetch(PROFILE_URL, {
  headers: {
    "User-Agent":
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
  },
});
if (!res.ok) {
  throw new Error(`Google Scholar returned HTTP ${res.status} — likely rate-limited; keeping existing data.`);
}
const html = await res.text();

const decode = (s) =>
  s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCharCode(parseInt(n, 16)));

// Sidebar stats table order: citations (all, since), h-index (all, since), i10 (all, since)
const stats = [...html.matchAll(/gsc_rsb_std">(\d+)</g)].map((m) => Number(m[1]));
if (stats.length < 5) {
  throw new Error("Failed to parse profile stats — Scholar HTML structure may have changed.");
}

const papers = [...html.matchAll(/<tr class="gsc_a_tr">([\s\S]*?)<\/tr>/g)]
  .map(([, row]) => {
    const title = row.match(/class="gsc_a_at"[^>]*>([^<]+)</)?.[1];
    const cites = row.match(/class="gsc_a_ac[^"]*"[^>]*>(\d*)</)?.[1];
    const year = row.match(/class="gsc_a_h[^"]*"[^>]*>(\d*)</)?.[1];
    return title ? { title: decode(title), citations: Number(cites || 0), year: year || "" } : null;
  })
  .filter(Boolean);

if (papers.length === 0) {
  throw new Error("Parsed zero papers — Scholar HTML structure may have changed.");
}

// No timestamp in the output: the file should only diff when the data itself
// changes, so the daily workflow commits only on real updates.
const body = `// AUTO-GENERATED by scripts/fetch-scholar.mjs — do not edit by hand.
// Source: https://scholar.google.com/citations?user=${SCHOLAR_USER}

export interface ScholarLivePaper {
  title: string;
  citations: number;
  year: string;
}

export const scholarLive = {
  stats: {
    totalCitations: ${stats[0]},
    hIndex: ${stats[2]},
    i10Index: ${stats[4]},
  },
  papers: ${JSON.stringify(papers, null, 2).replace(/"([a-z]+)":/gi, "$1:")} as ScholarLivePaper[],
};
`;

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
writeFileSync(join(root, "src/data/scholar-live.ts"), body);
console.log(
  `Updated scholar-live.ts: ${stats[0]} citations, h-index ${stats[2]}, i10 ${stats[4]}, ${papers.length} papers.`
);
