// One-off helper: pulls authoritative BibTeX (via doi.org content negotiation)
// and abstracts (via the Crossref API, where the publisher deposits them) for
// the publications in src/data/publications.ts, writing src/data/pubextras.ts.
// Re-run after adding new papers with DOIs:
//   node scripts/fetch-pubmeta.mjs

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const UA = "xiting-zhuang.github.io pubmeta fetcher (mailto:xiting.zhuang@ndsu.edu)";

// title -> DOI; null means "resolve by title search on Crossref"
const PUBS = [
  ["Tradition or tragedy: Arranged marriages and domestic violence", "10.1016/j.irle.2026.106343"],
  ["Public perspectives on food date labeling: Implications for waste reduction and food safety policy", "10.1016/j.foodpol.2026.103055"],
  ["Machine learning-assisted abstract screening on learning analytics: A step-by-step tutorial", "10.1186/s13643-026-03111-2"],
  ["Parental educational pairings and child physical abuse: Evidence from China", "10.1016/j.ijedudev.2025.103449"],
  ["Work environment and intimate partner violence against women: Evidence from China", "10.1080/00036846.2025.2590113"],
  ["Machine learning-assisted systematic review: A case study in learning analytics", "10.3390/educsci15111488"],
  ["The 2021 container shipping crisis and its consequences for US agricultural exports", null],
  ["Trade implications of ending China's zero-Covid policy", "10.46557/001c.137226"],
  ["Global container shipping disruptions, pop-up ports, and U.S. agricultural exports", "10.1002/aepp.13399"],
  ["The impact of maritime shipping disruptions on U.S. tree nut exports and inventories", "10.1002/agr.21809"],
  ["U.S. agricultural exports and the 2022 Mississippi River drought", "10.1002/agr.21880"],
  ["Supply chain disruptions and containerized agricultural exports from California ports", "10.1002/aepp.13311"],
  ["A portrait of firms that trade in meat products", "10.22004/ag.econ.329728"],
];

const stripJats = (s) =>
  s
    .replace(/<\/?jats:[^>]+>/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .replace(/^\s*Abstract\s*/i, "")
    .trim();

async function resolveDoi(title) {
  const url = `https://api.crossref.org/works?rows=1&query.bibliographic=${encodeURIComponent(title)}`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) return null;
  const item = (await res.json()).message?.items?.[0];
  if (!item) return null;
  const found = (item.title?.[0] || "").toLowerCase().replace(/[^a-z0-9]+/g, "");
  const want = title.toLowerCase().replace(/[^a-z0-9]+/g, "");
  // Require a real match before trusting a title search result.
  return found.slice(0, 40) === want.slice(0, 40) ? item.DOI : null;
}

const extras = {};
for (const [title, knownDoi] of PUBS) {
  const doi = knownDoi ?? (await resolveDoi(title));
  if (!doi) {
    console.warn(`SKIP (no DOI found): ${title.slice(0, 60)}`);
    continue;
  }
  const entry = { doi };

  const bibRes = await fetch(`https://doi.org/${doi}`, {
    headers: { Accept: "application/x-bibtex", "User-Agent": UA },
  });
  if (bibRes.ok) entry.bibtex = (await bibRes.text()).trim();

  const cr = await fetch(`https://api.crossref.org/works/${doi}`, {
    headers: { "User-Agent": UA },
  });
  if (cr.ok) {
    const msg = (await cr.json()).message;
    if (msg?.abstract) entry.abstract = stripJats(msg.abstract);
  }

  extras[title] = entry;
  console.log(`${doi}  bibtex:${entry.bibtex ? "y" : "n"} abstract:${entry.abstract ? "y" : "n"}  ${title.slice(0, 50)}`);
}

const body = `// AUTO-GENERATED by scripts/fetch-pubmeta.mjs — do not edit by hand.
// BibTeX from doi.org content negotiation; abstracts from Crossref where the
// publisher deposits them. Keyed by publication title as it appears in
// publications.ts.

export interface PubExtra {
  doi: string;
  bibtex?: string;
  abstract?: string;
}

export const pubExtras: Record<string, PubExtra> = ${JSON.stringify(extras, null, 2)};
`;

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
writeFileSync(join(root, "src/data/pubextras.ts"), body);
console.log(`\nWrote ${Object.keys(extras).length} entries to src/data/pubextras.ts`);
