// AUTO-GENERATED by scripts/fetch-pubmeta.mjs — do not edit by hand.
// BibTeX from doi.org content negotiation; abstracts from Crossref where the
// publisher deposits them. Keyed by publication title as it appears in
// publications.ts.

export interface PubExtra {
  doi: string;
  bibtex?: string;
  abstract?: string;
}

export const pubExtras: Record<string, PubExtra> = {
  "Tradition or tragedy: Arranged marriages and domestic violence": {
    "doi": "10.1016/j.irle.2026.106343",
    "bibtex": "@article{Tian_2026, title={Tradition or tragedy: Arranged marriages and domestic violence}, volume={87}, ISSN={0144-8188}, url={http://dx.doi.org/10.1016/j.irle.2026.106343}, DOI={10.1016/j.irle.2026.106343}, journal={International Review of Law and Economics}, publisher={Elsevier BV}, author={Tian, Weidong and Cao, Dongli and Zhuang, Xiting}, year={2026}, month=Sept, pages={106343} }"
  },
  "Public perspectives on food date labeling: Implications for waste reduction and food safety policy": {
    "doi": "10.1016/j.foodpol.2026.103055",
    "bibtex": "@article{Lu_2026, title={Public perspectives on food date labeling: implications for waste reduction and food safety policy}, volume={140}, ISSN={0306-9192}, url={http://dx.doi.org/10.1016/j.foodpol.2026.103055}, DOI={10.1016/j.foodpol.2026.103055}, journal={Food Policy}, publisher={Elsevier BV}, author={Lu, Peng and Mao, Lulu and Zhuang, Xiting and Xu, Zhihong and Ma, Shuai}, year={2026}, month=May, pages={103055} }"
  },
  "Machine learning-assisted abstract screening on learning analytics: A step-by-step tutorial": {
    "doi": "10.1186/s13643-026-03111-2",
    "bibtex": "@article{Xu_2026, title={Machine learning-assisted abstract screening on learning analytics: a step-by-step tutorial}, volume={15}, ISSN={2046-4053}, url={http://dx.doi.org/10.1186/s13643-026-03111-2}, DOI={10.1186/s13643-026-03111-2}, number={1}, journal={Systematic Reviews}, publisher={Springer Science and Business Media LLC}, author={Xu, Zhihong and Ma, Shuai and Zhuang, Xiting and Adeyemi, Anjorin Ezekiel and Kogut, Ashlynn}, year={2026}, month=Feb }"
  },
  "Parental educational pairings and child physical abuse: Evidence from China": {
    "doi": "10.1016/j.ijedudev.2025.103449",
    "bibtex": "@article{Tian_2025, title={Parental educational pairings and child physical abuse: Evidence from China}, volume={119}, ISSN={0738-0593}, url={http://dx.doi.org/10.1016/j.ijedudev.2025.103449}, DOI={10.1016/j.ijedudev.2025.103449}, journal={International Journal of Educational Development}, publisher={Elsevier BV}, author={Tian, Weidong and Dai, Zhiyong and Cao, Dongli and Zhuang, Xiting}, year={2025}, month=Nov, pages={103449} }"
  },
  "Work environment and intimate partner violence against women: Evidence from China": {
    "doi": "10.1080/00036846.2025.2590113",
    "bibtex": "@article{Tian_2025, title={Work environment and intimate partner violence against women: evidence from China}, ISSN={1466-4283}, url={http://dx.doi.org/10.1080/00036846.2025.2590113}, DOI={10.1080/00036846.2025.2590113}, journal={Applied Economics}, publisher={Informa UK Limited}, author={Tian, Weidong and Cao, Dongli and Zhuang, Xiting}, year={2025}, month=Nov, pages={1–14} }"
  },
  "Machine learning-assisted systematic review: A case study in learning analytics": {
    "doi": "10.3390/educsci15111488",
    "bibtex": "@article{Xu_2025, title={Machine Learning-Assisted Systematic Review: A Case Study in Learning Analytics}, volume={15}, ISSN={2227-7102}, url={http://dx.doi.org/10.3390/educsci15111488}, DOI={10.3390/educsci15111488}, number={11}, journal={Education Sciences}, publisher={MDPI AG}, author={Xu, Zhihong and Zhuang, Xiting and Ma, Shuai}, year={2025}, month=Nov, pages={1488} }",
    "abstract": "Traditional systematic reviews, despite their high-quality evidence, are labor-intensive and error-prone, especially during the abstract screening phase. This paper investigates the application of machine learning-assisted systematic reviewing in the context of Learning Analytics (LA) in higher education. This study evaluates two approaches—ASReview, an active traditional machine learning tool, and GPT-4o, a large language model—to automate this process. By comparing key performance metrics such as sensitivity, specificity, accuracy, precision, and F1-score, we assess the effectiveness of these tools against traditional manual methods. Our findings demonstrate the potential of machine learning to enhance the efficiency and accuracy of systematic reviews in learning analytics."
  },
  "The 2021 container shipping crisis and its consequences for US agricultural exports": {
    "doi": "10.3828/jtep.2025.59.2.110",
    "bibtex": "@article{Carter_2025, title={The 2021 Container Shipping Crisis and its Consequences for US Agricultural Exports}, volume={59}, ISSN={1754-5951}, url={http://dx.doi.org/10.3828/jtep.2025.59.2.110}, DOI={10.3828/jtep.2025.59.2.110}, number={2}, journal={Journal of Transport Economics and Policy}, publisher={Liverpool University Press}, author={Carter, Colin A. and Steinbach, Sandro and Zhuang, Xiting}, year={2025}, month=Apr, pages={110–136} }",
    "abstract": "This study examines the impact of the 2021 container shipping disruptions on US agricultural trade, utilising a non-linear panel event study methodology and detailed port-level trade data. We find that US containerised agricultural exports were 22 per cent lower than anticipated from May 2021 to January 2022, resulting in a considerable export loss of about USD 10 billion. Our analysis highlights regional and product-specific variations in trade effects, with ports in the Western and Southern USA experiencing the most severe impacts. We also document considerable treatment heterogeneity according to the customs region, export destination, freight costs, and local labour shortages."
  },
  "Trade implications of ending China's zero-Covid policy": {
    "doi": "10.46557/001c.137226",
    "bibtex": "@article{Steinbach_2025, title={Trade Implications of Ending China’s Zero-Covid Policy}, volume={6}, ISSN={2652-8681}, url={http://dx.doi.org/10.46557/001c.137226}, DOI={10.46557/001c.137226}, number={3}, journal={Asian Economics Letters}, publisher={Asia-Pacific Applied Economics Association}, author={Steinbach, Sandro and Zhuang, Xiting}, year={2025}, month=Sept }",
    "abstract": "This paper examines the trade implications following the termination of the zero-Covid policy in China. Our event studies indicate a 9.1 percent decline in exports and an 11.5 percent reduc-tion in imports during the first quarter after the policy was revoked. While exports showed a recovery with a 13.2 percent increase in the second quarter, imports continued to be subdued at 7.5 percent. Furthermore, we observe significant heterogeneity in trade response across trading partners, products, and Chinese provinces. Regions that implemented stricter Covid policies experienced more pronounced trade contractions, whereas those that received greater economic support during the pandemic demonstrated a stronger recovery in trade. Our findings under-score the substantial economic disruptions instigated by the Covid pandemic and illustrate the resilience of international trade in the face of the cessation of the zero-Covid policy in China."
  },
  "Global container shipping disruptions, pop-up ports, and U.S. agricultural exports": {
    "doi": "10.1002/aepp.13399",
    "bibtex": "@article{Steinbach_2023, title={Global container shipping disruptions, <scp>pop‐up</scp> ports, and US agricultural exports}, volume={46}, ISSN={2040-5804}, url={http://dx.doi.org/10.1002/aepp.13399}, DOI={10.1002/aepp.13399}, number={2}, journal={Applied Economic Perspectives and Policy}, publisher={Wiley}, author={Steinbach, Sandro and Zhuang, Xiting}, year={2023}, month=Sept, pages={553–571} }",
    "abstract": "This paper evaluates the impact of the Commodity Container Assistance Program on containerized agricultural exports from US ports. The program responded to logistical disruptions related to agricultural shipments from the ports of Oakland, Seattle, and Tacoma. Relying on counterfactual event study methods and detailed trade data, we find limited evidence of positive treatment effects after the program implementation. The average post‐event trade effect is 1.0%, leading to limited agricultural export gains of about $18.6 million per month between March and September 2022. These findings suggest that while the program was cost‐effective, it had limited success in facilitating US containerized agricultural exports."
  },
  "The impact of maritime shipping disruptions on U.S. tree nut exports and inventories": {
    "doi": "10.1002/agr.21809",
    "bibtex": "@article{Steinbach_2023, title={The impact of maritime shipping disruptions on US tree nut exports and inventories}, volume={39}, ISSN={1520-6297}, url={http://dx.doi.org/10.1002/agr.21809}, DOI={10.1002/agr.21809}, number={3}, journal={Agribusiness}, publisher={Wiley}, author={Steinbach, Sandro and Zhuang, Xiting}, year={2023}, month=Apr, pages={904–911} }",
    "abstract": "This paper assesses the impact of the 2021/22 maritime shipping disruptions on US tree nut exports and domestic inventories. Using detailed trade data for almonds, pistachios, and walnuts and counterfactual empirical methods that account for treatment dynamics, we estimate the trade response to maritime shipping disruptions at the US port and commodity level. We find that tree nut shipments were 457 million pounds or $943 million below the counterfactual between May 2021 and July 2022. Almonds experienced the brunt of those trade losses, while pistachio and walnut exports recorded smaller losses and recovered faster. Our estimates imply that maritime shipping disruptions are a primary driver of surging tree nut inventories. Without the trade destruction caused by maritime shipping disruptions, the almond inventory could have been 38.7% lower and close to the long‐run average in the 2021/22 marketing year. [EconLit Citations: F14, Q17]."
  },
  "U.S. agricultural exports and the 2022 Mississippi River drought": {
    "doi": "10.1002/agr.21880",
    "bibtex": "@article{Steinbach_2023, title={US agricultural exports and the 2022 Mississippi River drought}, volume={41}, ISSN={1520-6297}, url={http://dx.doi.org/10.1002/agr.21880}, DOI={10.1002/agr.21880}, number={1}, journal={Agribusiness}, publisher={Wiley}, author={Steinbach, Sandro and Zhuang, Xiting}, year={2023}, month=Dec, pages={289–303} }",
    "abstract": "This paper investigates the impact of the 2022 Mississippi River drought on agricultural trade using counterfactual evaluation methods and detailed trade data at the US port level. The study examines how the drought disrupted agricultural shipments out of Louisiana ports and whether the disruption led to trade diversion to other ports. Our findings reveal that shipments out of Louisiana ports were 3.9% or $560 million below the counterfactual between July 2022 and January 2023. In addition, the dynamic treatment estimates provide evidence of immediate trade recovery after the drought receded in October 2022, indicating that the impact of the drought was short‐lived. Wheat exports were the most affected, experiencing a reduction in shipments from Louisiana ports of $150 million and being diverted to US ports on the West Coast. In contrast, corn and soybeans did not experience lasting trade destruction or diversion to other ports. Our analysis also reveals that export prices increased significantly above the counterfactual level at Louisiana ports, suggesting that the drought impacted the supply and export dynamics of agricultural commodities. In conclusion, this paper provides valuable insights into the short‐run implications of natural disasters on agricultural trade. [EconLit Citations: F14, Q17]."
  },
  "Supply chain disruptions and containerized agricultural exports from California ports": {
    "doi": "10.1002/aepp.13311",
    "bibtex": "@article{Carter_2022, title={Supply chain disruptions and containerized agricultural exports from California ports}, volume={45}, ISSN={2040-5804}, url={http://dx.doi.org/10.1002/aepp.13311}, DOI={10.1002/aepp.13311}, number={2}, journal={Applied Economic Perspectives and Policy}, publisher={Wiley}, author={Carter, Colin A. and Steinbach, Sandro and Zhuang, Xiting}, year={2022}, month=July, pages={1051–1071} }",
    "abstract": "We study the trade effects of the 2021 supply chain disruptions on containerized agricultural exports from California ports. Our event studies show that port congestion and container shortages reduced agricultural exports by 22% from May to November 2021. The export losses exceed $3.2 billion and vary substantially across commodity groups, with California tree nut producers facing the brunt of the financial repercussions. California agriculture's losses surpass those from the 2018 China–US trade war by far. The export disruptions mirror the fact that California ports are among the least efficient globally."
  },
  "A portrait of firms that trade in meat products": {
    "doi": "10.22004/ag.econ.329728",
    "bibtex": "@article{https://doi.org/10.22004/ag.econ.329728,\n  doi = {10.22004/AG.ECON.329728},\n  url = {https://ageconsearch.umn.edu/record/329728},\n  author = {Schweizer, Heidi and Steinbach, Sandro and Zhuang, Xiting and Schweizer, Heidi and Steinbach, Sandro and Zhuang, Xiting},\n  keywords = {International Relations/Trade, Agribusiness},\n  language = {en},\n  title = {A Portrait of Firms that Trade in Meat Products},\n  publisher = {Unknown},\n  year = {2022}\n}"
  }
};
