// AUTO-GENERATED by scripts/fetch-scholar.mjs — do not edit by hand.
// Source: https://scholar.google.com/citations?user=7DWbsPUAAAAJ

export interface ScholarLivePaper {
  title: string;
  citations: number;
  year: string;
}

export const scholarLive = {
  stats: {
    totalCitations: 104,
    hIndex: 5,
    i10Index: 3,
  },
  papers: [
  {
    title: "Supply chain disruptions and containerized agricultural exports from California ports",
    citations: 32,
    year: "2023"
  },
  {
    title: "US agricultural exports and the 2022 Mississippi River drought",
    citations: 18,
    year: "2025"
  },
  {
    title: "\" Containergeddon\" and California Agriculture",
    citations: 11,
    year: "2021"
  },
  {
    title: "Global shipping container disruptions and US agricultural exports",
    citations: 8,
    year: "2022"
  },
  {
    title: "US agricultural trade challenges amid climate and geopolitical disruptions",
    citations: 6,
    year: "2024"
  },
  {
    title: "Ripple Effects of Shipping Lane Disruptions on U.S. Agriculture",
    citations: 4,
    year: "2024"
  },
  {
    title: "Soybean Basis Hits Record Low Amid Zero New-Crop Sales to China",
    citations: 3,
    year: "2025"
  },
  {
    title: "China Could Bypass US Soybeans in 2025/26 and IEEPA Tariffs Raise Input Costs",
    citations: 3,
    year: "2025"
  },
  {
    title: "Global container shipping disruptions, pop‐up ports, and US agricultural exports",
    citations: 3,
    year: "2024"
  },
  {
    title: "The impact of maritime shipping disruptions on US tree nut exports and inventories",
    citations: 3,
    year: "2023"
  },
  {
    title: "A One-Year Retrospective Assessment of China’s 2025/26 Retaliatory Tariffs on US Agricultural Exports",
    citations: 2,
    year: "2026"
  },
  {
    title: "IEEPA Fertilizer Tariffs: Revenue, Relief, and Pass-Through",
    citations: 2,
    year: "2026"
  },
  {
    title: "IEEPA Tariff Escalation: What It Means for US Food and Ag-Input Imports",
    citations: 2,
    year: "2025"
  },
  {
    title: "Global Container Trade Disruptions and US Agricultural Exports",
    citations: 2,
    year: "2022"
  },
  {
    title: "Tradition or tragedy: Arranged marriages and domestic violence",
    citations: 1,
    year: "2026"
  },
  {
    title: "Machine Learning-Assisted Systematic Review: A Case Study in Learning Analytics",
    citations: 1,
    year: "2025"
  },
  {
    title: "Supreme Court, Food and Input Tariff Relief, and Market Access Opportunities Through Recent Trade Deals",
    citations: 1,
    year: "2025"
  },
  {
    title: "Retaliatory Tariffs and Container Shipping Disruptions Cause Considerable Trade Damages to California’s Almond Industry",
    citations: 1,
    year: "2023"
  },
  {
    title: "A Portrait of Firms that Trade in Meat Products",
    citations: 1,
    year: "2022"
  },
  {
    title: "Bridging language and data: Transforming agricultural curricula for data analytics through linguistic insights",
    citations: 0,
    year: "2026"
  },
  {
    title: "The call of Kinship: How Clan culture shapes rural residents’ commitment to hometown development in China",
    citations: 0,
    year: "2026"
  },
  {
    title: "Public perspectives on food date labeling: implications for waste reduction and food safety policy",
    citations: 0,
    year: "2026"
  },
  {
    title: "NDSU Agricultural Trade Monitor",
    citations: 0,
    year: "2026"
  },
  {
    title: "How IEEPA Tariffs Shaped US Biofuel Feedstock Imports in 2025",
    citations: 0,
    year: "2026"
  },
  {
    title: "Machine learning-assisted abstract screening on learning analytics: a step-by-step tutorial",
    citations: 0,
    year: "2026"
  },
  {
    title: "Work environment and intimate partner violence against women: evidence from China",
    citations: 0,
    year: "2025"
  },
  {
    title: "Parental educational pairings and child physical abuse: Evidence from China",
    citations: 0,
    year: "2025"
  },
  {
    title: "The Gift of Equality: Legal Recognition of Same-Sex Unions and Domestic Violence Against the Elderly",
    citations: 0,
    year: "2025"
  },
  {
    title: "China’s Import Declines Reflect Broader Demand Weakness",
    citations: 0,
    year: "2025"
  },
  {
    title: "NDSU Agricultural Trade Monitor 2025-06",
    citations: 0,
    year: "2025"
  },
  {
    title: "Trade Implications of Ending China’s Zero-Covid Policy",
    citations: 0,
    year: "2025"
  },
  {
    title: "Implications of New US-China Deal, Soybean Commitments, Port Fee Suspension, and SE Asia Deals",
    citations: 0,
    year: "2025"
  },
  {
    title: "The 2021 Container Shipping Crisis and its Consequences for US Agricultural Exports",
    citations: 0,
    year: "2025"
  },
  {
    title: "Trade Shocks and Resilience of the Global Supply Chain: Chinese Trade Amid COVID-19",
    citations: 0,
    year: "2023"
  },
  {
    title: "The Time Varying Effect of the Covid-19 Pandemic on Agricultural Trade: Evidence from China",
    citations: 0,
    year: "2022"
  },
  {
    title: "A Journal of the Western Agricultural Economics Association Volume 20, Issue 2, Fall 2022",
    citations: 0,
    year: "2022"
  },
  {
    title: "Environmental Regulations, Waste Backhaul and Maritime Trade",
    citations: 0,
    year: "2021"
  },
  {
    title: "中国城市化进程对碳排放的影响研究——基于半参数面板空间滞后模型",
    citations: 0,
    year: "2017"
  },
  {
    title: "中国产出缺口对通货膨胀的影响研究",
    citations: 0,
    year: "2017"
  },
  {
    title: "Global Supply Chain and Domestic Trade Shocks",
    citations: 0,
    year: ""
  }
] as ScholarLivePaper[],
};
